baseURL = 'https://marx-a00.github.io/blog/'
languageCode = 'en-us'
title = 'Marcos Andrade | Blog'
publishDir = 'blog'

# Enable safe HTML rendering
[markup.goldmark.renderer]
  unsafe = true

# Use Hugo Modules to install the theme
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

# Additional settings
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
  env = "production"
  description = "Marcos Andrade's personal website and blog"
  author = "Marcos Andrade"
  # Site customization
  customCSS = ["css/style.css"]
  customJS = ["js/main.js"]

# Main menu
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30
