baseURL = 'https://marx-a00.github.io/'
languageCode = 'en-us'
title = 'Marcos Andrade | Full Stack Engineer'

# Enable safe HTML rendering
[markup.goldmark.renderer]
  unsafe = true

# Use Hugo Modules to install the theme
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

# Additional settings
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
  env = "production"
  description = "Marcos Andrade's personal website and blog"
  author = "Marcos Andrade"
  # You can add more theme-specific parameters here
